//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPProjectManagement.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectDetail()
        {
            this.ProjectTeamMembers = new HashSet<ProjectTeamMember>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> BusinessUnitId { get; set; }
        public Nullable<int> ProjectManagerId { get; set; }
        public Nullable<int> TeamLeadId { get; set; }
        public Nullable<int> BusinessCriticaId { get; set; }
        public Nullable<int> ProductOwnerId { get; set; }
        public Nullable<bool> TFS { get; set; }
        public Nullable<int> ProjectURLId { get; set; }
        public string Remarks { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual Project Project { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
        public virtual UserProfile UserProfile2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTeamMember> ProjectTeamMembers { get; set; }
        public virtual BusinessCritica BusinessCritica { get; set; }
        public virtual ProjectURL ProjectURL { get; set; }
    }
}
